{pkgs, ...}: let
  envTemp = "TRAOJUDGE_BUILD_TEMPDIR";
  envSrc = "TRAOJUDGE_BUILD_SOURCE";
  envOut = "TRAOJUDGE_BUILD_OUTPUT";
  cfg = {
    src = "\$${envSrc}";
    out = "\$${envOut}";
    temp = "\$${envTemp}";
  };
  /*
  return type: derivation
  $drv/output.json exists and the json satisfies schema below
  schema: {
    type: object,
    properties: {
      status: {
        type: string,
        enum: ["CE", "RE", "WA", "AC"]
      },
      testname: {
        type: string
      },
      source: {
        type: string
      },
      stdin: {
        type: string
      },
      actual_stdout: {
        type: string
      },
      expected_stdout: {
        type: string
      }
    }
  }
  */
  single-test-drv = {
    language-name, # type: string, example: "python3"
    testcase-name, # type: string, example: "test1"
    compile-cmd, # type: string, example: "cp -r src/* $out"
    run-cmd, # type: string, example: "python3 src/main.py"
    source, # type: string, example: "a = int(input())\nprint(a*2)"
    stdin, # type: string, example: "5"
    expected-stdout, # type: string, example: "10"
  }: let
    stdin-file = pkgs.writeTextFile {
      name = "stdin";
      text = stdin;
    };
    expected-stdout-file = pkgs.writeTextFile {
      name = "expected-stdout";
      text = expected-stdout;
    };
  in
    builtins.trace
    ''      Testing ${language-name}:${testcase-name} with
            compile-cmd:
              ${compile-cmd}
            run-cmd:
              ${run-cmd}
    ''
    pkgs.stdenv.mkDerivation rec {
      name = "test-${language-name}-${testcase-name}";
      src = pkgs.writeTextFile {
        name = "test-${language-name}-${testcase-name}-source";
        text = source;
        destination = "/main";
      };
      "${envSrc}" = "${src}/main";
      buildInputs = [
        pkgs.jq
      ];
      buildPhase = ''
        STATUS="AC"
        mkdir -p $out
        export "${envTemp}"="$out"/temp
        export "${envOut}"="$out"/output
        export STDIO_DIR="$out"/stdio
        export STDOUT_FILE=$STDIO_DIR/stdout.txt
        export STDERR_FILE=$STDIO_DIR/stderr.txt
        mkdir -p ${"$" + envOut}
        mkdir -p ${"$" + envTemp}
        mkdir -p $STDIO_DIR
        touch $STDOUT_FILE
        touch $STDERR_FILE
        if ! ${compile-cmd}; then
          echo "Compilation error for ${language-name} ${testcase-name}"
          STATUS="CE"
        else
          echo "Compilation successful for ${language-name} ${testcase-name}"
          echo "Running command: ${run-cmd} < ${stdin-file} > $STDOUT_FILE 2> $STDERR_FILE"
          if ! ${run-cmd} < ${stdin-file} > $STDOUT_FILE 2> $STDERR_FILE; then
            echo "Runtime error for ${language-name} ${testcase-name}"
            STATUS="RE"
          else
            echo "Running tests for ${language-name} ${testcase-name}"
            if diff -bB $STDOUT_FILE ${expected-stdout-file}; then
              echo "Test passed for ${language-name} ${testcase-name}"
            else
              echo "Test failed for ${language-name} ${testcase-name}"
              STATUS="WA"
            fi
          fi
        fi
        echo "${language-name}-${testcase-name}: $STATUS"
        jq -n \
          --arg status "$STATUS" \
          --arg testname "${testcase-name}" \
          --rawfile source "$src/main" \
          --rawfile stdin "${stdin-file}" \
          --rawfile expected_stdout "${expected-stdout-file}" \
          --rawfile actual_stdout "$STDOUT_FILE" \
          '{
            status: $status,
            testname: $testname,
            source: $source,
            stdin: $stdin,
            actual_stdout: $actual_stdout,
            expected_stdout: $expected_stdout
          }' > $out/output.json
      '';
    };

  # `single-test-result` will IFD the store object representing the test result generated by `single-test-drv`.
  single-test-result = args @ {
    language-name, # type: string, example: "python3"
    testcase-name, # type: string, example: "test1"
    compile-cmd, # type: string, example: "cp -r src/* $out"
    run-cmd, # type: string, example: "python3 src/main.py"
    source, # type: string, example: "a = int(input())\nprint(a*2)"
    stdin, # type: string, example: "5"
    expected-stdout, # type: string, example: "10"
  }: let
    drv = single-test-drv args;
    # ToDo: Validate JSON as store object using jsonschema
    result-expr = builtins.fromJSON (builtins.readFile "${drv}/output.json");
    result-expr-meets-schema = builtins.all (x: builtins.hasAttr x result-expr) [
      "status"
      "testname"
      "source"
      "stdin"
      "actual_stdout"
      "expected_stdout"
    ];
    tryeval-result = builtins.tryEval result-expr;
    tryeval-result-deep = builtins.deepSeq tryeval-result tryeval-result;
  in
    if tryeval-result-deep.success
    then
      if result-expr-meets-schema
      then {
        kind = "success";
        result = result-expr;
      }
      else {
        kind = "error";
        result = "Test result for ${language-name}:${testcase-name} does not meet the expected schema.";
      }
    else {
      kind = "error";
      result = "Test result for ${language-name}:${testcase-name} could not be evaluated";
    };

  # Returns test results for a language as nix expression.
  each-lang-test-result = {
    language,
    tests,
  }: {
    language = language.name;
    test-results =
      pkgs.lib.mapAttrsToList (testcase-name: testcase: (
        single-test-result {
          language-name = language.name;
          testcase-name = testcase-name;
          compile-cmd = language.compile cfg;
          run-cmd = language.run cfg;
          source = testcase.source;
          stdin = testcase.stdin;
          expected-stdout = testcase.stdout;
        }
      ))
      tests;
  };
in
  each-lang-test-result
