services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    privileged: true
    volumes:
      - nix_cache:/nix
      - ..:/workspace:cached

volumes:
  nix_cache:
