name: nix-fmt

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix fmt . && git diff --exit-code || (echo "Please run 'nix fmt' and commit the changes" && exit 1)
